version: "3.7"

services:
  calorie-db:
    container_name: calorie_app
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: calorie-db
    ports:
      - 5000:5432